spring:
  application:
    name: authentication_service
    version: testing

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/test
      client:
        registration:
          keycloak:
            client-id: test
            client-secret: HYaI9Z6Fs1yTHSiOJP1iujKKTexjOKRy
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8282/realms/test
            user-name-attribute: preferred_username



keycloak:
  realm: test
  domain: localhost:8282
  adminClientId: admin-cli
  adminClientSecret: HYaI9Z6Fs1yTHSiOJP1iujKKTexjOKRy
  urls:
    auth: http://${keycloak.domain}

server:
  port: 8084
